# -*- coding: utf-8 -*-
"""Sistema de Control de Cubetas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R-8fcg6PxcOcyI0kyuIR-QIg3sDjM-Xd
"""

from flask import Flask, request, redirect, url_for, render_template_string
import pymysql
from datetime import datetime

app = Flask(__name__)

# ==============================
# CONFIGURACIÓN DE LA BASE DE DATOS
# ==============================
# Configura estos parámetros con los datos de tu instancia EC2 o AWS RDS
#DB_HOST = "database-1.cnwwkmsi0zst.us-east-1.rds.amazonaws.com" # O 'localhost' si está en la misma EC2
DB_HOST = "database-1.c7eeqocsynzo.us-east-2.rds.amazonaws.com" # O 'localhost' nuevo en EC2 RDS
DB_USER = "admin"
DB_PASSWORD = "1234567890"
DB_NAME = "logistica_cubetas"

def get_connection(with_db=True):
    config = {
        "host": DB_HOST,
        "user": DB_USER,
        "password": DB_PASSWORD,
        "cursorclass": pymysql.cursors.DictCursor
    }
    if with_db:
        config["database"] = DB_NAME
    return pymysql.connect(**config)

def inicializar_bd():
    # Crear la base de datos si no existe
    conexion = get_connection(with_db=False)
    with conexion.cursor() as cursor:
        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {DB_NAME}")
    conexion.commit()
    conexion.close()

    # Crear la tabla principal de Kardex
    conexion = get_connection()
    with conexion.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS kardex_cubetas (
                id INT AUTO_INCREMENT PRIMARY KEY,
                fecha DATE NOT NULL,
                transportista VARCHAR(100) NOT NULL,
                cliente VARCHAR(100) NOT NULL,
                zona VARCHAR(100) NOT NULL,
                entregadas INT DEFAULT 0,
                retornadas INT DEFAULT 0,
                pendientes INT DEFAULT 0,
                fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        """)
    conexion.commit()
    conexion.close()

# ==============================
# INTERFAZ DE USUARIO (HTML + CSS + JS)
# ==============================
html_template = """
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kardex de Cubetas | Supply Chain</title>
    <style>
        :root {
            --primary: #004d99;
            --secondary: #f4f6f8;
            --success: #28a745;
            --danger: #dc3545;
            --dark: #333;
        }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; background-color: var(--secondary); color: var(--dark); }
        header { background-color: var(--primary); color: white; padding: 15px 20px; text-align: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        .container { max-width: 1200px; margin: 20px auto; padding: 0 15px; }

        /* Tabs System */
        .tabs { display: flex; border-bottom: 2px solid #ddd; margin-bottom: 20px; }
        .tab-btn { background: none; border: none; padding: 10px 20px; cursor: pointer; font-size: 16px; font-weight: bold; color: #666; }
        .tab-btn.active { color: var(--primary); border-bottom: 3px solid var(--primary); margin-bottom: -2px; }
        .tab-content { display: none; }
        .tab-content.active { display: block; }

        /* Formulario Móvil First */
        .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 20px; }
        .form-group { margin-bottom: 15px; }
        label { display: block; font-weight: bold; margin-bottom: 5px; color: var(--primary); }
        input[type="text"], input[type="number"], input[type="date"], select {
            width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; font-size: 16px;
        }
        button[type="submit"] {
            width: 100%; padding: 12px; background-color: var(--success); color: white; border: none; border-radius: 4px; font-size: 18px; cursor: pointer; font-weight: bold;
        }
        button[type="submit"]:hover { background-color: #218838; }

        /* Tablas Responsive */
        .table-responsive { overflow-x: auto; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; background: white; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; font-size: 14px; }
        th { background-color: var(--primary); color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .badge { padding: 4px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; color: white; }
        .bg-red { background-color: var(--danger); }
        .bg-green { background-color: var(--success); }

        /* Dashboard Cards */
        .dashboard-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
    </style>
</head>
<body>

<header>
    <h2>📦 Logística Inversa: Control de Cubetas</h2>
</header>

<div class="container">
    <div class="tabs">
        <button class="tab-btn active" onclick="openTab('registro')">📝 Registrar Visita</button>
        <button class="tab-btn" onclick="openTab('dashboard')">📊 Consolidado (Dashboard)</button>
    </div>

    <!-- PESTAÑA 1: FORMULARIO DE REGISTRO -->
    <div id="registro" class="tab-content active">
        <div class="card">
            <h3>Nuevo Registro de Entrega/Recogida</h3>
            <form method="POST" action="/guardar">
                <div class="form-group">
                    <label>Fecha de la Visita:</label>
                    <input type="date" name="fecha" required value="{{ fecha_hoy }}">
                </div>
                <div class="form-group">
                    <label>Nombre del Transportista:</label>
                    <input type="text" name="transportista" placeholder="Ej. Juan Pérez" required>
                </div>
                <div class="form-group">
                    <label>Nombre del Cliente:</label>
                    <input type="text" name="cliente" placeholder="Ej. Supermercado El Ahorro" required>
                </div>
                <div class="form-group">
                    <label>Zona / Ruta:</label>
                    <select name="zona" required>
                        <option value="">Seleccione una Zona</option>
                        <option value="Norte">Zona Norte</option>
                        <option value="Sur">Zona Sur</option>
                        <option value="Centro">Zona Centro</option>
                        <option value="Oriente">Zona Oriente</option>
                        <option value="Occidente">Zona Occidente</option>
                    </select>
                </div>
                <div style="display: flex; gap: 10px;">
                    <div class="form-group" style="flex: 1;">
                        <label>Cubetas Entregadas (Dejadas):</label>
                        <input type="number" name="entregadas" min="0" value="0" required>
                    </div>
                    <div class="form-group" style="flex: 1;">
                        <label>Cubetas Retornadas (Recogidas):</label>
                        <input type="number" name="retornadas" min="0" value="0" required>
                    </div>
                </div>
                <button type="submit">Guardar Registro en el Sistema</button>
            </form>
        </div>

        <div class="card">
            <h3>Últimos Movimientos (Kardex Diario)</h3>
            <div class="table-responsive">
                <table>
                    <tr>
                        <th>Fecha</th>
                        <th>Transportista</th>
                        <th>Cliente</th>
                        <th>Zona</th>
                        <th>Entregadas</th>
                        <th>Retornadas</th>
                        <th>Pendientes del viaje</th>
                    </tr>
                    {% for mov in movimientos %}
                    <tr>
                        <td>{{ mov.fecha }}</td>
                        <td>{{ mov.transportista }}</td>
                        <td>{{ mov.cliente }}</td>
                        <td>{{ mov.zona }}</td>
                        <td><span class="badge bg-red">+{{ mov.entregadas }}</span></td>
                        <td><span class="badge bg-green">-{{ mov.retornadas }}</span></td>
                        <td><strong>{{ mov.pendientes }}</strong></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <!-- PESTAÑA 2: DASHBOARD CONSOLIDADO -->
    <div id="dashboard" class="tab-content">
        <div class="dashboard-grid">
            <!-- Consolidado por Zona -->
            <div class="card">
                <h3>Resumen de Deuda por Zona</h3>
                <div class="table-responsive">
                    <table>
                        <tr>
                            <th>Zona</th>
                            <th>Total Cubetas Pendientes</th>
                        </tr>
                        {% for zona in resumen_zonas %}
                        <tr>
                            <td>{{ zona.zona }}</td>
                            <td style="font-size: 18px; font-weight: bold; color: {% if zona.total_pendientes > 0 %}#dc3545{% else %}#28a745{% endif %};">
                                {{ zona.total_pendientes }}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>

            <!-- Consolidado por Cliente -->
            <div class="card">
                <h3>Deuda Detallada por Cliente</h3>
                <div class="table-responsive">
                    <table>
                        <tr>
                            <th>Cliente</th>
                            <th>Zona</th>
                            <th>Saldo Pendiente</th>
                        </tr>
                        {% for cliente in resumen_clientes %}
                        <tr>
                            <td>{{ cliente.cliente }}</td>
                            <td>{{ cliente.zona }}</td>
                            <td style="font-weight: bold;">{{ cliente.total_pendientes }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function openTab(tabName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tab-content");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tab-btn");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(tabName).style.display = "block";
        event.currentTarget.className += " active";
    }
</script>

</body>
</html>
"""

# ==============================
# RUTAS DE LA APLICACIÓN
# ==============================

@app.route("/")
def index():
    try:
        inicializar_bd()
    except Exception as e:
        return f"Error conectando a la BD. Verifica credenciales y el Security Group en AWS. Detalle: {e}"

    conexion = get_connection()
    fecha_hoy = datetime.now().strftime('%Y-%m-%d')

    with conexion.cursor() as cursor:
        # 1. Obtener últimos movimientos
        cursor.execute("SELECT * FROM kardex_cubetas ORDER BY id DESC LIMIT 20")
        movimientos = cursor.fetchall()

        # 2. Obtener consolidado por Zona
        cursor.execute("""
            SELECT zona, SUM(pendientes) as total_pendientes
            FROM kardex_cubetas
            GROUP BY zona
            ORDER BY total_pendientes DESC
        """)
        resumen_zonas = cursor.fetchall()

        # 3. Obtener consolidado por Cliente
        cursor.execute("""
            SELECT cliente, zona, SUM(pendientes) as total_pendientes
            FROM kardex_cubetas
            GROUP BY cliente, zona
            HAVING total_pendientes != 0
            ORDER BY total_pendientes DESC
        """)
        resumen_clientes = cursor.fetchall()

    conexion.close()

    return render_template_string(
        html_template,
        movimientos=movimientos,
        resumen_zonas=resumen_zonas,
        resumen_clientes=resumen_clientes,
        fecha_hoy=fecha_hoy
    )

@app.route("/guardar", methods=["POST"])
def guardar_registro():
    fecha = request.form["fecha"]
    transportista = request.form["transportista"]
    cliente = request.form["cliente"]
    zona = request.form["zona"]
    entregadas = int(request.form["entregadas"])
    retornadas = int(request.form["retornadas"])

    # Lógica de Supply Chain: Las cubetas pendientes que quedan en deuda en esta transacción
    pendientes = entregadas - retornadas

    conexion = get_connection()
    with conexion.cursor() as cursor:
        cursor.execute("""
            INSERT INTO kardex_cubetas (fecha, transportista, cliente, zona, entregadas, retornadas, pendientes)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (fecha, transportista, cliente, zona, entregadas, retornadas, pendientes))
    conexion.commit()
    conexion.close()

    return redirect(url_for("index"))

# ==============================
# EJECUCIÓN DEL SERVIDOR
# ==============================
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
